// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RoomProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf {

  /// <summary>Holder for reflection information generated from RoomProto.proto</summary>
  public static partial class RoomProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for RoomProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RoomProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Sb29tUHJvdG8ucHJvdG8SD0dvb2dsZS5Qcm90b2J1ZiI5ChBQQl9DMlNM",
            "b2dpbkhlbGxvEhMKC2ZpZ2h0cm9vbWlkGAEgASgNEhAKCGhlbGxva2V5GAIg",
            "ASgJIj0KDVBCX1BsYXllckluZm8SCwoDcGlkGAEgASgEEhEKCXBsYXllcmlk",
            "eBgCIAEoBRIMCgRuYW1lGAMgASgJIhcKFVBCX0MyU0ZpZ2h0TG9hZGluZ0Vu",
            "ZCISChBQQl9TMkNGaWdodFN0YXJ0IhEKD1BCX0MyU0ZpZ2h0U091dCIfCg9Q",
            "Ql9Mb2FkaW5nQWdhaW4SDAoEdHlwZRgBIAEoDSI0Cg9QQl9DMlNGaWdodFNF",
            "bmQSDQoFaXN3aW4YASABKAgSEgoKcmVzdWx0ZmxhZxgCIAEoDSIeCg9QQl9T",
            "MkNGaWdodFNFbmQSCwoDZXhwGAEgASgNIp4BCg5QQl9DbGllbnRJbnB1dBIt",
            "CglJbnB1dFR5cGUYASABKA4yGi5Hb29nbGUuUHJvdG9idWYuSW5wdXRUeXBl",
            "Eg8KB0FuZ2xlX1gYAiABKAUSDwoHQW5nbGVfWRgDIAEoBRILCgNLZXkYBCAB",
            "KAUSDQoFUG9zX1gYBSABKAUSDQoFUG9zX1kYBiABKAUSEAoIVGFyZ2V0SUQY",
            "ByABKAUiRAoRUEJfQzJTQ2xpZW50SW5wdXQSLwoGaW5wdXRzGAEgAygLMh8u",
            "R29vZ2xlLlByb3RvYnVmLlBCX0NsaWVudElucHV0Ik8KDlBCX1BsYXllckZy",
            "YW1lEg0KBWluZGV4GAEgASgFEi4KBWlucHV0GAIgASgLMh8uR29vZ2xlLlBy",
            "b3RvYnVmLlBCX0NsaWVudElucHV0IlQKDFBCX0ZyYW1lSW5mbxITCgtmcmFt",
            "ZV9pbmRleBgBIAEoDRIvCgZpbnB1dHMYAiADKAsyHy5Hb29nbGUuUHJvdG9i",
            "dWYuUEJfUGxheWVyRnJhbWUqnQEKEExvYWRpbmdBZ2FpblR5cGUSGQoVTG9h",
            "ZGluZ0FnYWluVHlwZV9OT05FEAASGwoXQzJTX0xPQURJTkdfQUdBSU5fU1RB",
            "UlQQARIbChdTMkNfTE9BRElOR19BR0FJTl9TVEFSVBACEhkKFUMyU19MT0FE",
            "SU5HX0FHQUlOX0VORBADEhkKFVMyQ19MT0FESU5HX0FHQUlOX0VORBAEKoQC",
            "CglJbnB1dFR5cGUSEgoOSW5wdXRUeXBlX05PTkUQABIYChRJbnB1dFR5cGVf",
            "TU9WRV9TVEFSVBABEhgKFElucHV0VHlwZV9NT1ZFX0FOR0xFEAISFgoSSW5w",
            "dXRUeXBlX01PVkVfRU5EEAMSFgoSSW5wdXRUeXBlX0tFWV9ET1dOEAQSFAoQ",
            "SW5wdXRUeXBlX0tFWV9VUBAFEhwKGElucHV0VHlwZV9LRVlfTE9OR19TVEFS",
            "VBAGEhoKFklucHV0VHlwZV9LRVlfTE9OR19FTkQQBxIXChNJbnB1dFR5cGVf",
            "S0VZX0FOR0xFEAgSFgoSSW5wdXRUeXBlX0NMSUNLX1hZEAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.LoadingAgainType), typeof(global::Google.Protobuf.InputType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_C2SLoginHello), global::Google.Protobuf.PB_C2SLoginHello.Parser, new[]{ "Fightroomid", "Hellokey" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_PlayerInfo), global::Google.Protobuf.PB_PlayerInfo.Parser, new[]{ "Pid", "Playeridx", "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_C2SFightLoadingEnd), global::Google.Protobuf.PB_C2SFightLoadingEnd.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_S2CFightStart), global::Google.Protobuf.PB_S2CFightStart.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_C2SFightSOut), global::Google.Protobuf.PB_C2SFightSOut.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_LoadingAgain), global::Google.Protobuf.PB_LoadingAgain.Parser, new[]{ "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_C2SFightSEnd), global::Google.Protobuf.PB_C2SFightSEnd.Parser, new[]{ "Iswin", "Resultflag" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_S2CFightSEnd), global::Google.Protobuf.PB_S2CFightSEnd.Parser, new[]{ "Exp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_ClientInput), global::Google.Protobuf.PB_ClientInput.Parser, new[]{ "InputType", "AngleX", "AngleY", "Key", "PosX", "PosY", "TargetID" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_C2SClientInput), global::Google.Protobuf.PB_C2SClientInput.Parser, new[]{ "Inputs" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_PlayerFrame), global::Google.Protobuf.PB_PlayerFrame.Parser, new[]{ "Index", "Input" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.PB_FrameInfo), global::Google.Protobuf.PB_FrameInfo.Parser, new[]{ "FrameIndex", "Inputs" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum LoadingAgainType {
    [pbr::OriginalName("LoadingAgainType_NONE")] None = 0,
    /// <summary>
    ///客户端战斗中资源加载开始
    /// </summary>
    [pbr::OriginalName("C2S_LOADING_AGAIN_START")] C2SLoadingAgainStart = 1,
    /// <summary>
    ///客户端战斗中资源加载开始
    /// </summary>
    [pbr::OriginalName("S2C_LOADING_AGAIN_START")] S2CLoadingAgainStart = 2,
    /// <summary>
    ///客户端战斗中资源加载完成
    /// </summary>
    [pbr::OriginalName("C2S_LOADING_AGAIN_END")] C2SLoadingAgainEnd = 3,
    /// <summary>
    ///客户端战斗中资源加载完成
    /// </summary>
    [pbr::OriginalName("S2C_LOADING_AGAIN_END")] S2CLoadingAgainEnd = 4,
  }

  public enum InputType {
    [pbr::OriginalName("InputType_NONE")] None = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_MOVE_START")] MoveStart = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_MOVE_ANGLE")] MoveAngle = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_MOVE_END")] MoveEnd = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_KEY_DOWN")] KeyDown = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_KEY_UP")] KeyUp = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_KEY_LONG_START")] KeyLongStart = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_KEY_LONG_END")] KeyLongEnd = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_KEY_ANGLE")] KeyAngle = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("InputType_CLICK_XY")] ClickXy = 9,
  }

  #endregion

  #region Messages
  /// <summary>
  ///C2S_LOGIN_HELLO 登陆请求
  /// </summary>
  public sealed partial class PB_C2SLoginHello : pb::IMessage<PB_C2SLoginHello> {
    private static readonly pb::MessageParser<PB_C2SLoginHello> _parser = new pb::MessageParser<PB_C2SLoginHello>(() => new PB_C2SLoginHello());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_C2SLoginHello> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SLoginHello() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SLoginHello(PB_C2SLoginHello other) : this() {
      fightroomid_ = other.fightroomid_;
      hellokey_ = other.hellokey_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SLoginHello Clone() {
      return new PB_C2SLoginHello(this);
    }

    /// <summary>Field number for the "fightroomid" field.</summary>
    public const int FightroomidFieldNumber = 1;
    private uint fightroomid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Fightroomid {
      get { return fightroomid_; }
      set {
        fightroomid_ = value;
      }
    }

    /// <summary>Field number for the "hellokey" field.</summary>
    public const int HellokeyFieldNumber = 2;
    private string hellokey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Hellokey {
      get { return hellokey_; }
      set {
        hellokey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_C2SLoginHello);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_C2SLoginHello other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Fightroomid != other.Fightroomid) return false;
      if (Hellokey != other.Hellokey) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Fightroomid != 0) hash ^= Fightroomid.GetHashCode();
      if (Hellokey.Length != 0) hash ^= Hellokey.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Fightroomid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Fightroomid);
      }
      if (Hellokey.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Hellokey);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Fightroomid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Fightroomid);
      }
      if (Hellokey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Hellokey);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_C2SLoginHello other) {
      if (other == null) {
        return;
      }
      if (other.Fightroomid != 0) {
        Fightroomid = other.Fightroomid;
      }
      if (other.Hellokey.Length != 0) {
        Hellokey = other.Hellokey;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Fightroomid = input.ReadUInt32();
            break;
          }
          case 18: {
            Hellokey = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PB_PlayerInfo : pb::IMessage<PB_PlayerInfo> {
    private static readonly pb::MessageParser<PB_PlayerInfo> _parser = new pb::MessageParser<PB_PlayerInfo>(() => new PB_PlayerInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_PlayerInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerInfo(PB_PlayerInfo other) : this() {
      pid_ = other.pid_;
      playeridx_ = other.playeridx_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerInfo Clone() {
      return new PB_PlayerInfo(this);
    }

    /// <summary>Field number for the "pid" field.</summary>
    public const int PidFieldNumber = 1;
    private ulong pid_;
    /// <summary>
    ///游戏服ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Pid {
      get { return pid_; }
      set {
        pid_ = value;
      }
    }

    /// <summary>Field number for the "playeridx" field.</summary>
    public const int PlayeridxFieldNumber = 2;
    private int playeridx_;
    /// <summary>
    ///战斗房间服临时分配ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Playeridx {
      get { return playeridx_; }
      set {
        playeridx_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 3;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_PlayerInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_PlayerInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Pid != other.Pid) return false;
      if (Playeridx != other.Playeridx) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Pid != 0UL) hash ^= Pid.GetHashCode();
      if (Playeridx != 0) hash ^= Playeridx.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Pid != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Pid);
      }
      if (Playeridx != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Playeridx);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Pid != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Pid);
      }
      if (Playeridx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Playeridx);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_PlayerInfo other) {
      if (other == null) {
        return;
      }
      if (other.Pid != 0UL) {
        Pid = other.Pid;
      }
      if (other.Playeridx != 0) {
        Playeridx = other.Playeridx;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Pid = input.ReadUInt64();
            break;
          }
          case 16: {
            Playeridx = input.ReadInt32();
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///C2S_FIGHT_LOADING_END 客户端资源加载完成
  /// </summary>
  public sealed partial class PB_C2SFightLoadingEnd : pb::IMessage<PB_C2SFightLoadingEnd> {
    private static readonly pb::MessageParser<PB_C2SFightLoadingEnd> _parser = new pb::MessageParser<PB_C2SFightLoadingEnd>(() => new PB_C2SFightLoadingEnd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_C2SFightLoadingEnd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightLoadingEnd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightLoadingEnd(PB_C2SFightLoadingEnd other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightLoadingEnd Clone() {
      return new PB_C2SFightLoadingEnd(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_C2SFightLoadingEnd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_C2SFightLoadingEnd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_C2SFightLoadingEnd other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  ///S2C_FIGHT_START 副本战斗开始
  /// </summary>
  public sealed partial class PB_S2CFightStart : pb::IMessage<PB_S2CFightStart> {
    private static readonly pb::MessageParser<PB_S2CFightStart> _parser = new pb::MessageParser<PB_S2CFightStart>(() => new PB_S2CFightStart());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_S2CFightStart> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightStart() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightStart(PB_S2CFightStart other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightStart Clone() {
      return new PB_S2CFightStart(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_S2CFightStart);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_S2CFightStart other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_S2CFightStart other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  /// <summary>
  ///玩家中途强制退出战斗
  /// </summary>
  public sealed partial class PB_C2SFightSOut : pb::IMessage<PB_C2SFightSOut> {
    private static readonly pb::MessageParser<PB_C2SFightSOut> _parser = new pb::MessageParser<PB_C2SFightSOut>(() => new PB_C2SFightSOut());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_C2SFightSOut> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSOut() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSOut(PB_C2SFightSOut other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSOut Clone() {
      return new PB_C2SFightSOut(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_C2SFightSOut);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_C2SFightSOut other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_C2SFightSOut other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class PB_LoadingAgain : pb::IMessage<PB_LoadingAgain> {
    private static readonly pb::MessageParser<PB_LoadingAgain> _parser = new pb::MessageParser<PB_LoadingAgain>(() => new PB_LoadingAgain());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_LoadingAgain> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_LoadingAgain() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_LoadingAgain(PB_LoadingAgain other) : this() {
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_LoadingAgain Clone() {
      return new PB_LoadingAgain(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private uint type_;
    /// <summary>
    ///LoadingAgainType
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_LoadingAgain);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_LoadingAgain other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_LoadingAgain other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端结束战斗逻辑
  /// </summary>
  public sealed partial class PB_C2SFightSEnd : pb::IMessage<PB_C2SFightSEnd> {
    private static readonly pb::MessageParser<PB_C2SFightSEnd> _parser = new pb::MessageParser<PB_C2SFightSEnd>(() => new PB_C2SFightSEnd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_C2SFightSEnd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSEnd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSEnd(PB_C2SFightSEnd other) : this() {
      iswin_ = other.iswin_;
      resultflag_ = other.resultflag_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SFightSEnd Clone() {
      return new PB_C2SFightSEnd(this);
    }

    /// <summary>Field number for the "iswin" field.</summary>
    public const int IswinFieldNumber = 1;
    private bool iswin_;
    /// <summary>
    ///战斗胜利/失败结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Iswin {
      get { return iswin_; }
      set {
        iswin_ = value;
      }
    }

    /// <summary>Field number for the "resultflag" field.</summary>
    public const int ResultflagFieldNumber = 2;
    private uint resultflag_;
    /// <summary>
    ///战斗逻辑结果特征值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Resultflag {
      get { return resultflag_; }
      set {
        resultflag_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_C2SFightSEnd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_C2SFightSEnd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Iswin != other.Iswin) return false;
      if (Resultflag != other.Resultflag) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Iswin != false) hash ^= Iswin.GetHashCode();
      if (Resultflag != 0) hash ^= Resultflag.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Iswin != false) {
        output.WriteRawTag(8);
        output.WriteBool(Iswin);
      }
      if (Resultflag != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Resultflag);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Iswin != false) {
        size += 1 + 1;
      }
      if (Resultflag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Resultflag);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_C2SFightSEnd other) {
      if (other == null) {
        return;
      }
      if (other.Iswin != false) {
        Iswin = other.Iswin;
      }
      if (other.Resultflag != 0) {
        Resultflag = other.Resultflag;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Iswin = input.ReadBool();
            break;
          }
          case 16: {
            Resultflag = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///战斗失败/胜利后退出战斗,及结算信息
  /// </summary>
  public sealed partial class PB_S2CFightSEnd : pb::IMessage<PB_S2CFightSEnd> {
    private static readonly pb::MessageParser<PB_S2CFightSEnd> _parser = new pb::MessageParser<PB_S2CFightSEnd>(() => new PB_S2CFightSEnd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_S2CFightSEnd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightSEnd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightSEnd(PB_S2CFightSEnd other) : this() {
      exp_ = other.exp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_S2CFightSEnd Clone() {
      return new PB_S2CFightSEnd(this);
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 1;
    private uint exp_;
    /// <summary>
    ///获得的经验值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_S2CFightSEnd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_S2CFightSEnd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Exp != other.Exp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Exp != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Exp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_S2CFightSEnd other) {
      if (other == null) {
        return;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Exp = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PB_ClientInput : pb::IMessage<PB_ClientInput> {
    private static readonly pb::MessageParser<PB_ClientInput> _parser = new pb::MessageParser<PB_ClientInput>(() => new PB_ClientInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_ClientInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_ClientInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_ClientInput(PB_ClientInput other) : this() {
      inputType_ = other.inputType_;
      angleX_ = other.angleX_;
      angleY_ = other.angleY_;
      key_ = other.key_;
      posX_ = other.posX_;
      posY_ = other.posY_;
      targetID_ = other.targetID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_ClientInput Clone() {
      return new PB_ClientInput(this);
    }

    /// <summary>Field number for the "InputType" field.</summary>
    public const int InputTypeFieldNumber = 1;
    private global::Google.Protobuf.InputType inputType_ = 0;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.InputType InputType {
      get { return inputType_; }
      set {
        inputType_ = value;
      }
    }

    /// <summary>Field number for the "Angle_X" field.</summary>
    public const int AngleXFieldNumber = 2;
    private int angleX_;
    /// <summary>
    ///InputType_MOVE_ANGLE,InputType_KEY_ANGLE时
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AngleX {
      get { return angleX_; }
      set {
        angleX_ = value;
      }
    }

    /// <summary>Field number for the "Angle_Y" field.</summary>
    public const int AngleYFieldNumber = 3;
    private int angleY_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int AngleY {
      get { return angleY_; }
      set {
        angleY_ = value;
      }
    }

    /// <summary>Field number for the "Key" field.</summary>
    public const int KeyFieldNumber = 4;
    private int key_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "Pos_X" field.</summary>
    public const int PosXFieldNumber = 5;
    private int posX_;
    /// <summary>
    ///InputType_CLICK_XY时
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "Pos_Y" field.</summary>
    public const int PosYFieldNumber = 6;
    private int posY_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "TargetID" field.</summary>
    public const int TargetIDFieldNumber = 7;
    private int targetID_;
    /// <summary>
    ///目标ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetID {
      get { return targetID_; }
      set {
        targetID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_ClientInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_ClientInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InputType != other.InputType) return false;
      if (AngleX != other.AngleX) return false;
      if (AngleY != other.AngleY) return false;
      if (Key != other.Key) return false;
      if (PosX != other.PosX) return false;
      if (PosY != other.PosY) return false;
      if (TargetID != other.TargetID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InputType != 0) hash ^= InputType.GetHashCode();
      if (AngleX != 0) hash ^= AngleX.GetHashCode();
      if (AngleY != 0) hash ^= AngleY.GetHashCode();
      if (Key != 0) hash ^= Key.GetHashCode();
      if (PosX != 0) hash ^= PosX.GetHashCode();
      if (PosY != 0) hash ^= PosY.GetHashCode();
      if (TargetID != 0) hash ^= TargetID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InputType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) InputType);
      }
      if (AngleX != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AngleX);
      }
      if (AngleY != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(AngleY);
      }
      if (Key != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Key);
      }
      if (PosX != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(PosX);
      }
      if (PosY != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(PosY);
      }
      if (TargetID != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(TargetID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InputType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) InputType);
      }
      if (AngleX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AngleX);
      }
      if (AngleY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AngleY);
      }
      if (Key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Key);
      }
      if (PosX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosX);
      }
      if (PosY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PosY);
      }
      if (TargetID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_ClientInput other) {
      if (other == null) {
        return;
      }
      if (other.InputType != 0) {
        InputType = other.InputType;
      }
      if (other.AngleX != 0) {
        AngleX = other.AngleX;
      }
      if (other.AngleY != 0) {
        AngleY = other.AngleY;
      }
      if (other.Key != 0) {
        Key = other.Key;
      }
      if (other.PosX != 0) {
        PosX = other.PosX;
      }
      if (other.PosY != 0) {
        PosY = other.PosY;
      }
      if (other.TargetID != 0) {
        TargetID = other.TargetID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            inputType_ = (global::Google.Protobuf.InputType) input.ReadEnum();
            break;
          }
          case 16: {
            AngleX = input.ReadInt32();
            break;
          }
          case 24: {
            AngleY = input.ReadInt32();
            break;
          }
          case 32: {
            Key = input.ReadInt32();
            break;
          }
          case 40: {
            PosX = input.ReadInt32();
            break;
          }
          case 48: {
            PosY = input.ReadInt32();
            break;
          }
          case 56: {
            TargetID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///C2S_INPUT_INFO 客户端输入
  /// </summary>
  public sealed partial class PB_C2SClientInput : pb::IMessage<PB_C2SClientInput> {
    private static readonly pb::MessageParser<PB_C2SClientInput> _parser = new pb::MessageParser<PB_C2SClientInput>(() => new PB_C2SClientInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_C2SClientInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SClientInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SClientInput(PB_C2SClientInput other) : this() {
      inputs_ = other.inputs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_C2SClientInput Clone() {
      return new PB_C2SClientInput(this);
    }

    /// <summary>Field number for the "inputs" field.</summary>
    public const int InputsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Protobuf.PB_ClientInput> _repeated_inputs_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Protobuf.PB_ClientInput.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.PB_ClientInput> inputs_ = new pbc::RepeatedField<global::Google.Protobuf.PB_ClientInput>();
    /// <summary>
    ///输入
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.PB_ClientInput> Inputs {
      get { return inputs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_C2SClientInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_C2SClientInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!inputs_.Equals(other.inputs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= inputs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      inputs_.WriteTo(output, _repeated_inputs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += inputs_.CalculateSize(_repeated_inputs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_C2SClientInput other) {
      if (other == null) {
        return;
      }
      inputs_.Add(other.inputs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            inputs_.AddEntriesFrom(input, _repeated_inputs_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PB_PlayerFrame : pb::IMessage<PB_PlayerFrame> {
    private static readonly pb::MessageParser<PB_PlayerFrame> _parser = new pb::MessageParser<PB_PlayerFrame>(() => new PB_PlayerFrame());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_PlayerFrame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerFrame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerFrame(PB_PlayerFrame other) : this() {
      index_ = other.index_;
      Input = other.input_ != null ? other.Input.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_PlayerFrame Clone() {
      return new PB_PlayerFrame(this);
    }

    /// <summary>Field number for the "index" field.</summary>
    public const int IndexFieldNumber = 1;
    private int index_;
    /// <summary>
    ///玩家INDEX
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Index {
      get { return index_; }
      set {
        index_ = value;
      }
    }

    /// <summary>Field number for the "input" field.</summary>
    public const int InputFieldNumber = 2;
    private global::Google.Protobuf.PB_ClientInput input_;
    /// <summary>
    ///玩家输入
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.PB_ClientInput Input {
      get { return input_; }
      set {
        input_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_PlayerFrame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_PlayerFrame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Index != other.Index) return false;
      if (!object.Equals(Input, other.Input)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Index != 0) hash ^= Index.GetHashCode();
      if (input_ != null) hash ^= Input.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Index != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Index);
      }
      if (input_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Input);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Index != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Index);
      }
      if (input_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Input);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_PlayerFrame other) {
      if (other == null) {
        return;
      }
      if (other.Index != 0) {
        Index = other.Index;
      }
      if (other.input_ != null) {
        if (input_ == null) {
          input_ = new global::Google.Protobuf.PB_ClientInput();
        }
        Input.MergeFrom(other.Input);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Index = input.ReadInt32();
            break;
          }
          case 18: {
            if (input_ == null) {
              input_ = new global::Google.Protobuf.PB_ClientInput();
            }
            input.ReadMessage(input_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///S2C_FRAME_INFO 一帧数据
  /// </summary>
  public sealed partial class PB_FrameInfo : pb::IMessage<PB_FrameInfo> {
    private static readonly pb::MessageParser<PB_FrameInfo> _parser = new pb::MessageParser<PB_FrameInfo>(() => new PB_FrameInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PB_FrameInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.RoomProtoReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FrameInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FrameInfo(PB_FrameInfo other) : this() {
      frameIndex_ = other.frameIndex_;
      inputs_ = other.inputs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PB_FrameInfo Clone() {
      return new PB_FrameInfo(this);
    }

    /// <summary>Field number for the "frame_index" field.</summary>
    public const int FrameIndexFieldNumber = 1;
    private uint frameIndex_;
    /// <summary>
    ///帧编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint FrameIndex {
      get { return frameIndex_; }
      set {
        frameIndex_ = value;
      }
    }

    /// <summary>Field number for the "inputs" field.</summary>
    public const int InputsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Protobuf.PB_PlayerFrame> _repeated_inputs_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Protobuf.PB_PlayerFrame.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.PB_PlayerFrame> inputs_ = new pbc::RepeatedField<global::Google.Protobuf.PB_PlayerFrame>();
    /// <summary>
    ///帧信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Protobuf.PB_PlayerFrame> Inputs {
      get { return inputs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PB_FrameInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PB_FrameInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrameIndex != other.FrameIndex) return false;
      if(!inputs_.Equals(other.inputs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FrameIndex != 0) hash ^= FrameIndex.GetHashCode();
      hash ^= inputs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FrameIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(FrameIndex);
      }
      inputs_.WriteTo(output, _repeated_inputs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FrameIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FrameIndex);
      }
      size += inputs_.CalculateSize(_repeated_inputs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PB_FrameInfo other) {
      if (other == null) {
        return;
      }
      if (other.FrameIndex != 0) {
        FrameIndex = other.FrameIndex;
      }
      inputs_.Add(other.inputs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            FrameIndex = input.ReadUInt32();
            break;
          }
          case 18: {
            inputs_.AddEntriesFrom(input, _repeated_inputs_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
