# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notify.proto',
  package='Google.Protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x0cnotify.proto\x12\x0fGoogle.Protobuf\"\x1e\n\x0fPB_NotifyNarmal\x12\x0b\n\x03Msg\x18\x01 \x01(\t\"/\n\x0fPB_NotifyOption\x12\x0b\n\x03Idx\x18\x01 \x01(\x05\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\"\xcd\x01\n\x12PB_NotifyOptionMsg\x12\x13\n\x0bResprondIdx\x18\x01 \x01(\x05\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0b\n\x03Msg\x18\x03 \x01(\t\x12\r\n\x05NpcID\x18\x04 \x01(\x05\x12\x10\n\x08NpcShape\x18\x05 \x01(\x05\x12\x0f\n\x07NpcName\x18\x06 \x01(\x05\x12\x0f\n\x07TemplID\x18\x07 \x01(\x05\x12\x10\n\x08ShowTime\x18\x08 \x01(\x05\x12\x31\n\x07Options\x18\t \x03(\x0b\x32 .Google.Protobuf.PB_NotifyOption\"\x99\x01\n\x11PB_NotifyInputMsg\x12\x13\n\x0bResprondIdx\x18\x01 \x01(\x05\x12\r\n\x05Title\x18\x02 \x01(\t\x12\x0b\n\x03Msg\x18\x03 \x01(\t\x12\r\n\x05NpcID\x18\x04 \x01(\x05\x12\x10\n\x08NpcShape\x18\x05 \x01(\x05\x12\x0f\n\x07NpcName\x18\x06 \x01(\x05\x12\x0f\n\x07TemplID\x18\x07 \x01(\x05\x12\x10\n\x08ShowTime\x18\x08 \x01(\x05\"C\n\x11PB_NotifyProgress\x12\x13\n\x0bResprondIdx\x18\x01 \x01(\x05\x12\x0c\n\x04Time\x18\x02 \x01(\t\x12\x0b\n\x03Msg\x18\x03 \x01(\t\"\x1e\n\x0ePB_NotifyClear\x12\x0c\n\x04Type\x18\x01 \x01(\x05\"9\n\x15PB_NotifyOptionAnswer\x12\x13\n\x0bResprondIdx\x18\x01 \x01(\x05\x12\x0b\n\x03Idx\x18\x02 \x01(\x05\"<\n\x14PB_NotifyInputAnswer\x12\x13\n\x0bResprondIdx\x18\x01 \x01(\x05\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t*\xd9\x01\n\x0bNotifyMsgID\x12\x15\n\x11S2C_NOTIFY_NARMAL\x10\x00\x12\x19\n\x15S2C_NOTIFY_OPTION_MSG\x10\x01\x12\x14\n\x10S2C_NOTIFY_INPUT\x10\x02\x12\x17\n\x13S2C_NOTIFY_PROGRESS\x10\x06\x12\x14\n\x10S2C_NOTIFY_CLEAR\x10\x07\x12\x1d\n\x19\x43\x32GS_NOTIFY_OPTION_ANSWER\x10\x08\x12\x1c\n\x18\x43\x32GS_NOTIFY_INPUT_ANSWER\x10\t\x12\x16\n\x12S2C_GOLDEQUIP_HINT\x10\nb\x06proto3')
)

_NOTIFYMSGID = _descriptor.EnumDescriptor(
  name='NotifyMsgID',
  full_name='Google.Protobuf.NotifyMsgID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S2C_NOTIFY_NARMAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_NOTIFY_OPTION_MSG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_NOTIFY_INPUT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_NOTIFY_PROGRESS', index=3, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_NOTIFY_CLEAR', index=4, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2GS_NOTIFY_OPTION_ANSWER', index=5, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2GS_NOTIFY_INPUT_ANSWER', index=6, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_GOLDEQUIP_HINT', index=7, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=701,
  serialized_end=918,
)
_sym_db.RegisterEnumDescriptor(_NOTIFYMSGID)

NotifyMsgID = enum_type_wrapper.EnumTypeWrapper(_NOTIFYMSGID)
S2C_NOTIFY_NARMAL = 0
S2C_NOTIFY_OPTION_MSG = 1
S2C_NOTIFY_INPUT = 2
S2C_NOTIFY_PROGRESS = 6
S2C_NOTIFY_CLEAR = 7
C2GS_NOTIFY_OPTION_ANSWER = 8
C2GS_NOTIFY_INPUT_ANSWER = 9
S2C_GOLDEQUIP_HINT = 10



_PB_NOTIFYNARMAL = _descriptor.Descriptor(
  name='PB_NotifyNarmal',
  full_name='Google.Protobuf.PB_NotifyNarmal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Msg', full_name='Google.Protobuf.PB_NotifyNarmal.Msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=63,
)


_PB_NOTIFYOPTION = _descriptor.Descriptor(
  name='PB_NotifyOption',
  full_name='Google.Protobuf.PB_NotifyOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Idx', full_name='Google.Protobuf.PB_NotifyOption.Idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='Google.Protobuf.PB_NotifyOption.Content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=112,
)


_PB_NOTIFYOPTIONMSG = _descriptor.Descriptor(
  name='PB_NotifyOptionMsg',
  full_name='Google.Protobuf.PB_NotifyOptionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResprondIdx', full_name='Google.Protobuf.PB_NotifyOptionMsg.ResprondIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='Google.Protobuf.PB_NotifyOptionMsg.Title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='Google.Protobuf.PB_NotifyOptionMsg.Msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcID', full_name='Google.Protobuf.PB_NotifyOptionMsg.NpcID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcShape', full_name='Google.Protobuf.PB_NotifyOptionMsg.NpcShape', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcName', full_name='Google.Protobuf.PB_NotifyOptionMsg.NpcName', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TemplID', full_name='Google.Protobuf.PB_NotifyOptionMsg.TemplID', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ShowTime', full_name='Google.Protobuf.PB_NotifyOptionMsg.ShowTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Options', full_name='Google.Protobuf.PB_NotifyOptionMsg.Options', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=320,
)


_PB_NOTIFYINPUTMSG = _descriptor.Descriptor(
  name='PB_NotifyInputMsg',
  full_name='Google.Protobuf.PB_NotifyInputMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResprondIdx', full_name='Google.Protobuf.PB_NotifyInputMsg.ResprondIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Title', full_name='Google.Protobuf.PB_NotifyInputMsg.Title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='Google.Protobuf.PB_NotifyInputMsg.Msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcID', full_name='Google.Protobuf.PB_NotifyInputMsg.NpcID', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcShape', full_name='Google.Protobuf.PB_NotifyInputMsg.NpcShape', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NpcName', full_name='Google.Protobuf.PB_NotifyInputMsg.NpcName', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TemplID', full_name='Google.Protobuf.PB_NotifyInputMsg.TemplID', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ShowTime', full_name='Google.Protobuf.PB_NotifyInputMsg.ShowTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=476,
)


_PB_NOTIFYPROGRESS = _descriptor.Descriptor(
  name='PB_NotifyProgress',
  full_name='Google.Protobuf.PB_NotifyProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResprondIdx', full_name='Google.Protobuf.PB_NotifyProgress.ResprondIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Time', full_name='Google.Protobuf.PB_NotifyProgress.Time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='Google.Protobuf.PB_NotifyProgress.Msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=545,
)


_PB_NOTIFYCLEAR = _descriptor.Descriptor(
  name='PB_NotifyClear',
  full_name='Google.Protobuf.PB_NotifyClear',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='Google.Protobuf.PB_NotifyClear.Type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=577,
)


_PB_NOTIFYOPTIONANSWER = _descriptor.Descriptor(
  name='PB_NotifyOptionAnswer',
  full_name='Google.Protobuf.PB_NotifyOptionAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResprondIdx', full_name='Google.Protobuf.PB_NotifyOptionAnswer.ResprondIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Idx', full_name='Google.Protobuf.PB_NotifyOptionAnswer.Idx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=636,
)


_PB_NOTIFYINPUTANSWER = _descriptor.Descriptor(
  name='PB_NotifyInputAnswer',
  full_name='Google.Protobuf.PB_NotifyInputAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResprondIdx', full_name='Google.Protobuf.PB_NotifyInputAnswer.ResprondIdx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='Google.Protobuf.PB_NotifyInputAnswer.Content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=698,
)

_PB_NOTIFYOPTIONMSG.fields_by_name['Options'].message_type = _PB_NOTIFYOPTION
DESCRIPTOR.message_types_by_name['PB_NotifyNarmal'] = _PB_NOTIFYNARMAL
DESCRIPTOR.message_types_by_name['PB_NotifyOption'] = _PB_NOTIFYOPTION
DESCRIPTOR.message_types_by_name['PB_NotifyOptionMsg'] = _PB_NOTIFYOPTIONMSG
DESCRIPTOR.message_types_by_name['PB_NotifyInputMsg'] = _PB_NOTIFYINPUTMSG
DESCRIPTOR.message_types_by_name['PB_NotifyProgress'] = _PB_NOTIFYPROGRESS
DESCRIPTOR.message_types_by_name['PB_NotifyClear'] = _PB_NOTIFYCLEAR
DESCRIPTOR.message_types_by_name['PB_NotifyOptionAnswer'] = _PB_NOTIFYOPTIONANSWER
DESCRIPTOR.message_types_by_name['PB_NotifyInputAnswer'] = _PB_NOTIFYINPUTANSWER
DESCRIPTOR.enum_types_by_name['NotifyMsgID'] = _NOTIFYMSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PB_NotifyNarmal = _reflection.GeneratedProtocolMessageType('PB_NotifyNarmal', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYNARMAL,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyNarmal)
  ))
_sym_db.RegisterMessage(PB_NotifyNarmal)

PB_NotifyOption = _reflection.GeneratedProtocolMessageType('PB_NotifyOption', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYOPTION,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyOption)
  ))
_sym_db.RegisterMessage(PB_NotifyOption)

PB_NotifyOptionMsg = _reflection.GeneratedProtocolMessageType('PB_NotifyOptionMsg', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYOPTIONMSG,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyOptionMsg)
  ))
_sym_db.RegisterMessage(PB_NotifyOptionMsg)

PB_NotifyInputMsg = _reflection.GeneratedProtocolMessageType('PB_NotifyInputMsg', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYINPUTMSG,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyInputMsg)
  ))
_sym_db.RegisterMessage(PB_NotifyInputMsg)

PB_NotifyProgress = _reflection.GeneratedProtocolMessageType('PB_NotifyProgress', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYPROGRESS,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyProgress)
  ))
_sym_db.RegisterMessage(PB_NotifyProgress)

PB_NotifyClear = _reflection.GeneratedProtocolMessageType('PB_NotifyClear', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYCLEAR,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyClear)
  ))
_sym_db.RegisterMessage(PB_NotifyClear)

PB_NotifyOptionAnswer = _reflection.GeneratedProtocolMessageType('PB_NotifyOptionAnswer', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYOPTIONANSWER,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyOptionAnswer)
  ))
_sym_db.RegisterMessage(PB_NotifyOptionAnswer)

PB_NotifyInputAnswer = _reflection.GeneratedProtocolMessageType('PB_NotifyInputAnswer', (_message.Message,), dict(
  DESCRIPTOR = _PB_NOTIFYINPUTANSWER,
  __module__ = 'notify_pb2'
  # @@protoc_insertion_point(class_scope:Google.Protobuf.PB_NotifyInputAnswer)
  ))
_sym_db.RegisterMessage(PB_NotifyInputAnswer)


# @@protoc_insertion_point(module_scope)
