// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Assets/Script/Behaviors/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: YeGuaiAI

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoop_bt_YeGuaiAI_node0 : behaviac.DecoratorLoop
	{
		public DecoratorLoop_bt_YeGuaiAI_node0()
		{
			m_bDecorateWhenChildEnds = true;
			m_bDoneWithinFrame = false;
		}
		protected override int GetCount(Agent pAgent)
		{
			return -1;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoopUntil_bt_YeGuaiAI_node5 : behaviac.DecoratorLoopUntil
	{
		public DecoratorLoopUntil_bt_YeGuaiAI_node5()
		{
			m_bDecorateWhenChildEnds = true;
			m_until = true;
		}
		protected override int GetCount(Agent pAgent)
		{
			return -1;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_YeGuaiAI_node6 : behaviac.Action
	{
		public Action_bt_YeGuaiAI_node6()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((YeGuaiAI)pAgent).FindEnmey();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_YeGuaiAI_node9 : behaviac.Condition
	{
		public Condition_bt_YeGuaiAI_node9()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			bool opl = ((YeGuaiAI)pAgent).PursuitOrAttack();
			bool opr = true;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_YeGuaiAI_node10 : behaviac.Action
	{
		public Action_bt_YeGuaiAI_node10()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((YeGuaiAI)pAgent).Attack();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_YeGuaiAI_node11 : behaviac.Action
	{
		public Action_bt_YeGuaiAI_node11()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((YeGuaiAI)pAgent).Pursuit();
			return EBTStatus.BT_SUCCESS;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_YeGuaiAI_node8 : behaviac.Action
	{
		public Action_bt_YeGuaiAI_node8()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((YeGuaiAI)pAgent).IsOutRang();
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoopUntil_bt_YeGuaiAI_node12 : behaviac.DecoratorLoopUntil
	{
		public DecoratorLoopUntil_bt_YeGuaiAI_node12()
		{
			m_bDecorateWhenChildEnds = true;
			m_until = true;
		}
		protected override int GetCount(Agent pAgent)
		{
			return -1;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_YeGuaiAI_node13 : behaviac.Action
	{
		public Action_bt_YeGuaiAI_node13()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((YeGuaiAI)pAgent).BackHome();
			return result;
		}
	}

	public static class bt_YeGuaiAI
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("YeGuaiAI");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("YeGuaiAI");
#endif
			// children
			{
				DecoratorLoop_bt_YeGuaiAI_node0 node0 = new DecoratorLoop_bt_YeGuaiAI_node0();
				node0.SetClassNameString("DecoratorLoop");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("YeGuaiAI");
#endif
				bt.AddChild(node0);
				{
					Sequence node1 = new Sequence();
					node1.SetClassNameString("Sequence");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("YeGuaiAI");
#endif
					node0.AddChild(node1);
					{
						Sequence node2 = new Sequence();
						node2.SetClassNameString("Sequence");
						node2.SetId(2);
#if !BEHAVIAC_RELEASE
						node2.SetAgentType("YeGuaiAI");
#endif
						node1.AddChild(node2);
						{
							DecoratorLoopUntil_bt_YeGuaiAI_node5 node5 = new DecoratorLoopUntil_bt_YeGuaiAI_node5();
							node5.SetClassNameString("DecoratorLoopUntil");
							node5.SetId(5);
#if !BEHAVIAC_RELEASE
							node5.SetAgentType("YeGuaiAI");
#endif
							node2.AddChild(node5);
							{
								Action_bt_YeGuaiAI_node6 node6 = new Action_bt_YeGuaiAI_node6();
								node6.SetClassNameString("Action");
								node6.SetId(6);
#if !BEHAVIAC_RELEASE
								node6.SetAgentType("YeGuaiAI");
#endif
								node5.AddChild(node6);
								node5.SetHasEvents(node5.HasEvents() | node6.HasEvents());
							}
							node2.SetHasEvents(node2.HasEvents() | node5.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node2.HasEvents());
					}
					{
						Sequence node3 = new Sequence();
						node3.SetClassNameString("Sequence");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("YeGuaiAI");
#endif
						node1.AddChild(node3);
						{
							IfElse node7 = new IfElse();
							node7.SetClassNameString("IfElse");
							node7.SetId(7);
#if !BEHAVIAC_RELEASE
							node7.SetAgentType("YeGuaiAI");
#endif
							node3.AddChild(node7);
							{
								Condition_bt_YeGuaiAI_node9 node9 = new Condition_bt_YeGuaiAI_node9();
								node9.SetClassNameString("Condition");
								node9.SetId(9);
#if !BEHAVIAC_RELEASE
								node9.SetAgentType("YeGuaiAI");
#endif
								node7.AddChild(node9);
								node7.SetHasEvents(node7.HasEvents() | node9.HasEvents());
							}
							{
								Action_bt_YeGuaiAI_node10 node10 = new Action_bt_YeGuaiAI_node10();
								node10.SetClassNameString("Action");
								node10.SetId(10);
#if !BEHAVIAC_RELEASE
								node10.SetAgentType("YeGuaiAI");
#endif
								node7.AddChild(node10);
								node7.SetHasEvents(node7.HasEvents() | node10.HasEvents());
							}
							{
								Action_bt_YeGuaiAI_node11 node11 = new Action_bt_YeGuaiAI_node11();
								node11.SetClassNameString("Action");
								node11.SetId(11);
#if !BEHAVIAC_RELEASE
								node11.SetAgentType("YeGuaiAI");
#endif
								node7.AddChild(node11);
								node7.SetHasEvents(node7.HasEvents() | node11.HasEvents());
							}
							node3.SetHasEvents(node3.HasEvents() | node7.HasEvents());
						}
						{
							Action_bt_YeGuaiAI_node8 node8 = new Action_bt_YeGuaiAI_node8();
							node8.SetClassNameString("Action");
							node8.SetId(8);
#if !BEHAVIAC_RELEASE
							node8.SetAgentType("YeGuaiAI");
#endif
							node3.AddChild(node8);
							node3.SetHasEvents(node3.HasEvents() | node8.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node3.HasEvents());
					}
					{
						Sequence node4 = new Sequence();
						node4.SetClassNameString("Sequence");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("YeGuaiAI");
#endif
						node1.AddChild(node4);
						{
							DecoratorLoopUntil_bt_YeGuaiAI_node12 node12 = new DecoratorLoopUntil_bt_YeGuaiAI_node12();
							node12.SetClassNameString("DecoratorLoopUntil");
							node12.SetId(12);
#if !BEHAVIAC_RELEASE
							node12.SetAgentType("YeGuaiAI");
#endif
							node4.AddChild(node12);
							{
								Action_bt_YeGuaiAI_node13 node13 = new Action_bt_YeGuaiAI_node13();
								node13.SetClassNameString("Action");
								node13.SetId(13);
#if !BEHAVIAC_RELEASE
								node13.SetAgentType("YeGuaiAI");
#endif
								node12.AddChild(node13);
								node12.SetHasEvents(node12.HasEvents() | node13.HasEvents());
							}
							node4.SetHasEvents(node4.HasEvents() | node12.HasEvents());
						}
						node1.SetHasEvents(node1.HasEvents() | node4.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
